# Generated by Django 4.2.4 on 2023-10-15 14:03

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('car_title', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('customer_need', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
                ('message', ckeditor.fields.RichTextField()),
                ('create_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
