# Generated by Django 4.2.4 on 2023-10-17 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inquiry', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inquiry',
            new_name='Inquire',
        ),
    ]
