# Generated by Django 4.1.3 on 2023-01-10 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='facebook_link',
        ),
    ]
