# Generated by Django 4.1.3 on 2023-01-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_team_facebook_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='facebook_link',
            field=models.URLField(default=5),
            preserve_default=False,
        ),
    ]
