# Generated by Django 4.1.3 on 2023-01-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_car_car_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='car_id',
        ),
        migrations.AlterField(
            model_name='car',
            name='id',
            field=models.IntegerField(default=True, primary_key=True, serialize=False),
        ),
    ]
