# Generated by Django 4.2.4 on 2023-10-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_remove_car_car_id_alter_car_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
